### ISSUE TITLE
Where is the git_wrapper library from?

### ISSUE THREAD

**Issue by da1nerd** [unfoldingWord-dev/ts-server#8]
@jag3773 for documentation purposes can you please identify what library this is https://github.com/unfoldingWord-dev/ts-server/blob/master/server.py#L10? 

It looks like it may be https://github.com/msiemens/PyGitUp/blob/master/PyGitUp/git_wrapper.py.

**Comment by jag3773** [comment]
Ha, that would be cool, but no it's from https://github.com/unfoldingWord-dev/tools/blob/master/general_tools/git_wrapper.py.
